getwd()
setwd("C://Users//ilopez//OneDrive - Superintendencia de Bancos de la Republica Dominicana//Documentos//Data Science Specialization//Data_Science_Specialization//Curso 5")
library(dplyr)
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip",destfile = "data.zip")
data <- read.csv("data//activity.csv")
head(data)
str(data)
summary(data)
hist(data$steps,main = "Histogram of Steps",xlab = "Steps",col="lightblue")
mean_and_median_per_day<-data%>%group_by(date)%>%summarise_at(vars(steps), list(mean = mean,median=median))
plot(mean_and_median_per_day$mean,type = "line",ylab = "Average Steps")
maximum_which<-data%>%group_by(date)%>%summarise_at(vars(steps), list(max = which.max))
mean(maximum_which$max)
sum(data$steps%>%is.na)
data$steps <- data$steps %>% replace(is.na(.), mean(data$steps,na.rm=T))
total_per_day<-data%>%group_by(date)%>%summarise_at(vars(steps), list(total = sum))
hist(total_per_day$total,xlab="Total Steps",main="Histogram of total steps")
summary(total_per_day)
weekdays1 <- c('lunes', 'martes', 'miércoles', 'jueves', 'viernes')
#Use `%in%` and `weekdays` to create a logical vector
#convert to `factor` and specify the `levels/labels`
data$weekday <- factor((weekdays(as.Date(data$date)) %in% weekdays1), 
                   levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))
average<-data%>%group_by(weekday,date)%>%summarise_at(vars(steps), list(mean = mean))
par(mfrow=c(1,2))
plot(average[average$weekday=="weekday",]$mean,type = "l",ylab = "mean",main = "Weekday")
abline(h=average[average$weekday=="weekday",]$mean%>%mean)
plot(average[average$weekday=="weekend",]$mean,type = "l",ylab = "mean",main="Weekend")
abline(h=average[average$weekday=="weekend",]$mean%>%mean)
